# Site settings
title: DSSG Berlin
longtitle: Data Science for Social Good Berlin
email: contact@dssg-berlin.org
volunteer_email: volunteer@dssg-berlin.org
description: > # this means to ignore newlines until "baseurl:"
  We make mission-driven organizations aware of their data’s value and facilitate the support of the data science community to answer the emerging questions.
  We mediate between mission driven organizations and the data science community to create customized data dives that create solutions for the identified data problems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dssg-berlin.org" # the base hostname & protocol for your site
twitter_username: dssgber
github_username:  dssg-berlin

# Build settings
markdown: kramdown

gems: [bourbon, neat]
