# Site settings
title: Data Science for Social Good Berlin
email: contact@dssg-berlin.org
volunteer_email: volunteer@dssg-berlin.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://dssg-berlin.org" # the base hostname & protocol for your site
twitter_username: dssgber
github_username:  dssg-berlin

# Build settings
markdown: kramdown

gems: [bourbon, neat]
